### ISSUE TITLE
[Docs]: Setup a contributing md file for new contributors

### ISSUE THREAD

**Issue by samyakshah3008** [samyakshah3008/pomo-super-focus-webapp#87]
## Description: 

PomoSuperFocus is on initial phase of development and we need to setup a contributing guide for newcomers! 💙

**Comment by Lagaress** [comment]
@samyakshah3008 Can I help with this?

**Comment by samyakshah3008** [comment]
Sure @Lagaress , please go ahead! Thanks for raising your hand! ⚡🚀💙
Have assigned you this issue ticket!

**Comment by Lagaress** [comment]
I've created a PR to solve this issue: #90. Please [review](https://github.com/samyakshah3008/pomo-super-focus-webapp/pull/90) when it's possible @samyakshah3008

**Comment by samyakshah3008** [comment]
Thanks for your PR @Lagaress  - I am reviewing in a while! 😄 💙⚡

**Comment by Lagaress** [comment]
I think everything has been solved, take a look at it when you can @samyakshah3008
